export const arrayItems = [
    {
      id: "1",
      name: "ألبرت أينشتاين",
      img: "https://img.freepik.com/premium-vector/albert-einstein-cartoon-character-has-idea_324746-781.jpg?w=740",
      description: "let us talk",
      prompt: "imagine you are albert einstein",
      option: {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        top_p: 1,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
      },
    },
    {
      id: "2",
      name: "إسحاق نيوتن",
      img: "https://st2.depositphotos.com/3973669/5723/v/600/depositphotos_57234507-stock-illustration-illustrator-of-isaac-newton.jpg",
      description: "let us talk",
      prompt: "imagine you are isaac newton",
      option: {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        top_p: 1,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
      },
    },
    {
      id: "3",
      name: "أدولف هتلر",
      img: "https://cdn.pixabay.com/photo/2017/05/12/03/55/adolf-hitler-2306007_1280.png",
      description: "let us talk",
      prompt: "imagine you are adolf hitler",
      option: {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        top_p: 1,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
      },
    },
    {
      id: "4",
      name: "وينستون تشرشل",
      img: "https://cdn.dribbble.com/users/543350/screenshots/5252073/winston_still_2x.gif?compress=1&resize=400x300",
      description: "let us talk",
      prompt: "imagine you are winston churchill",
      option: {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        top_p: 1,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
      },
    },
    {
      id: "5",
      name: "جوزيف ستالين",
      img: "https://media.istockphoto.com/id/623711004/vector/military-of-north-korea-cartoon-character-vector-illustration.jpg?s=612x612&w=0&k=20&c=GTs4BPzjzSPi5DmX-5Tg3l8vPHC8GVP99jKI3t5f14k=",
      description: "let us talk",
      prompt: "imagine you are joseph stalin",
      option: {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        top_p: 1,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
      },
    },
    {
      id: "6",
      name: "حنبعل",
      img: "https://thumbs.dreamstime.com/b/hannibal-cartoon-character-vector-illustration-kids-history-collection-hannibal-cartoon-character-vector-illustration-112222399.jpg",
      description: "let us talk",
      prompt: "imagine you are hannibal",
      option: {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        top_p: 1,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
      },
    }
  ];